name: deploy

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v4
         - name: Deploy to EC2
           uses: appleboy/ssh-action@v1.0.3
           with:
            host: ${{ secrets.HOST }}
            username: ubuntu
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
             cd ~/Uniwallet_Project
             git pull origin main
             sudo npm install
             sudo npm run build
             sudo pm2 restart uniwallet || pm2 start npm --name uniwallet -- start
 

        